# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: /

jobs:
# Please do not rename this job
  build-project:
    name: build ficcon-website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          CI: true
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_FROM_EMAIL: ${{ secrets.RESEND_FROM_EMAIL }}
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          SITE_URL: ${{ inputs.site-url }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          npm ci
          npm start

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: bd0be4ea-448c-4028-b37f-7450231a1908
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/ficcon-website/config.yaml
          action: upload
